### ISSUE TITLE
[Feature Request] Enterprise Linux Packages

### ISSUE THREAD

**Issue by console-cowboy** [madrisan/nagios-plugins-linux#130]
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe.
It is currently possible to build packages for Red Hat Family distros such as Fedora and CentOS Stream, but the option to build packages for stable Enterprise Linux distributions (RHEL / AlmaLinux / RockyLinux) does not exist.

## Describe the solution you'd like
I would like to request the addition and support of Enterprise Linux builds for this collection of plugins.

## Describe alternatives you've considered
There's not a particular alternative to this request beyond eventually contributing some implementation of this feature. This may take some time however, as I'd have to take some time to review how the docker-based build system specific to this repository works before I can make and test changes. Besides that, I could build the binaries and simply copy them to compatible hosts, but this is an inelegant solution that is worse to manage and orchestrate.

**Comment by madrisan** [comment]
Thanks for opening this feature request!
Supporting RHEL5+ was my main goal when I was working as sysadmin. These OSes are still hopefully supported by nagios-plugins-linux, but AFAICS downloading a container image for RHEL still requires a valid RedHat subscription. That's why I cannot see how to integrate the rpm package creation.
I think you can successfully use the specfile for Fedora and create the packages with a simple `rpm -ba nagios-plugins-linux.spec`.
I'll try to make some tests to check if this is a viable solution.

**Comment by console-cowboy** [comment]
Thanks for looking into this; I'm all but certain you'd be able to produce a RHEL compatible build by compiling with either an [AlmaLinux](https://almalinux.org/) or [Rocky Linux](https://rockylinux.org/) container, both of which promise 1:1 binary compatibility with EL and serve as successors to CentOS as it existed prior to introduction of Stream.

**Comment by madrisan** [comment]
Ok. Feature in progress, using Rocky Linux.
Will be available soon. Don't forget to add a star to this project in the meantime ;)
