### ISSUE TITLE
not see Configure file 

### ISSUE THREAD

**Issue by DRAKUN** [madrisan/nagios-plugins-linux#6]
Hi , i'm new in nagios community, i have a problem to integrate nagios-plugin-linux in my nagios plugin folder.

I can't compile because i don't see the configure file and i don't know how to generate that.

Please someone can help me

**Comment by madrisan** [comment]
Hi DRAKUN,
the configure script can be generated by running the command `autoreconf --install` (see the [README.md](https://github.com/madrisan/nagios-plugins-linux/blob/master/README.md) file). That's why you do not see this file in the git repository.
I recommend you to download the [tarball of the v20](https://github.com/madrisan/nagios-plugins-linux/releases/tag/v20) where the configure script is present.

**Comment by madrisan** [comment]
I close this issue - feel free to reopen if necessary.
